[build-system]
  requires = ["setuptools"]
  build-backend = "setuptools.build_meta"

[project]
  name = "penelope"
  version = "0.10.0"
  requires-python = ">=3.6"

[tool.setuptools]
  script-files = ["penelope.py"]
